### ISSUE TITLE
Online Inference on a custom DB

### ISSUE THREAD

**Issue by hotessy** [huybery/r2sql#3]
Hi, 
Can you please help us out with the steps to run queries on a custom database?

**Comment by huybery** [comment]
Hi, you could replace the data and re-run the preprocess step for custom database.
Now this repo it mainly focus on SParC & CoSQL datasets, so there is no corresponding custom run script open.

**Comment by hotessy** [comment]
Thanks, @huybery. 
So, every time a new utterance is created by the user, we need to run the pre-processing script? Is there a way for evaluating utterances in an interaction _without_ pre-processing and re-instantiating the model? 
I'm building an app on top of your model and a fair amount of the time goes into re-loading the model. Is there any _hack_ to achieve online inference/ streamed training?

**Comment by huybery** [comment]
@hotessy , sorry to have kept you waiting.
This project is the research subsidiary code of the paper, so it may need to do more transformation in the application, but I may not have more energy to transform it at present. If you have ideas, welcome to improve it. 😄
